---
title: "BUAN6356_Group8_Project_CreditCardFraud"
author: "Stacey Kirkpatrick"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_notebook:
    theme: spacelab
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Load packages

```{r loadpackages, warning=FALSE, message=FALSE, results='hide'}

if(!require("pacman")) install.packages("pacman")
pacman::p_load(data.table, tidyverse, ggplot2, ggcorrplot, pROC, ROSE,gains,
              corrplot, dplyr, caret, MASS, caTools, smotefamily, DMwR, rpart)

theme_set(theme_classic())
```
## Read CSV file and create DataTable 

```{r readData}

## Read CSV file
cc <- read.csv("creditcard.csv")

## Examine the structure of the data set
str(cc)

##Descriptive stats
summary(cc)

## Create the data.table
credit.dt <- setDT(cc)
credit.dt

#Descriptive stats by Class
temp1 <- credit.dt[, .(min.amount=min(Amount), max.amount=max(Amount), mean.amount=mean(Amount), med.amount=median(Amount), sd.amount=sd(Amount)), by=Class]
temp1

##Check for missing values
colSums(is.na(cc))
```

```{r exploreClassImbalance}

##Checking Class imbalance
table(credit.dt$Class)

#Percentage of Class imbalance
100*prop.table(table(credit.dt$Class))

common_theme <- theme(plot.title = element_text(hjust = 0.5, face = "bold"))

ggplot(data = credit.dt, aes(x = factor(Class), y = prop.table(stat(count)), 
                             fill = factor(Class),
                             label = scales::percent(prop.table(stat(count))))) +
  scale_fill_brewer(palette = "Set2") +
  geom_bar(position = "dodge") +
  geom_text(stat = 'count',
            position = position_dodge(.9),
            vjust = -0.5,
            size = 3) +
  scale_x_discrete(labels = c("no fraud", "fraud")) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = 'Class', y = 'Percentage') + 
  ggtitle ("Distribution of Class Variable") +
  common_theme
```

```{r exploreCorrelation}

#Correlations
correlations <- cor(credit.dt[,], method="pearson")
round(correlations, 2)
##title <- "Correlation of Fraud Dataset Variables"
corrplot(correlations, number.cex = .9, type = "upper",
              method = "color", tl.cex=0.8,tl.col = "black")


```

```{r exploreTime}

credit.dt %>%
  ggplot(aes(x = Time, fill = factor(Class))) + geom_histogram(bins = 100)+
  labs(x = 'Time in Seconds Since First Transaction', y = 'No. of Transactions') +
  ggtitle('Distribution of Time of Transaction by Class') +
  scale_fill_brewer(palette = "Set2") +
  facet_grid(Class ~ ., scales = 'free_y') + common_theme


```


```{r exploreAmount}

ggplot(credit.dt, aes(x = factor(Class), y = Amount)) + geom_boxplot() + 
labs(x = 'Class (Non-Fraud vs Fraud)', y = 'Amount (Euros)') +
ggtitle("Distribution of Transaction Amount by Class") + common_theme


credit.dt %>%
  ggplot(aes(x = Amount)) + geom_histogram(col="black", fill = "darkseagreen3")+
  labs(x = 'Amount < 300 Euros', y = 'Frequency') +
  ggtitle('Distribution of Amount < 300 Euros') + xlim(c(0,300))+ ylim(c(0,30000)) +
                                  common_theme

```
```{r prepData}

##caret::featurePlot(x=credit.dt[,2:29], y=credit.dt[,31])

#Remove 'Time' variable
cc.data <- credit.dt[,-1]


#Change 'Class' variable to factor
cc.data$Class <- as.factor(cc.data$Class)
levels(cc.data$Class) <- c("Not_Fraud", "Fraud")

head(cc.data)
```
```{r splitData}

#Set seed to make partition reproducible
set.seed(123) 

#Train 70% of the dataset
train.index <- sample(1:nrow(cc.data), 
                   round(dim(cc.data) [1]*0.7))  

#Collect all the columns with training row ID into training set
train.data <- cc.data[train.index, ]

#Remaining 30% of dataset for validation
test.data <- cc.data[-train.index, ]

head(train.data)
head(test.data)

```

```{r classRatio}
# Initial Class Ratio for Training Data

tab <- table(train.data$Class)
tab

```

```{r downsampling}
set.seed(12345)
down_train <- downSample(x = train.data[, -30],
                         y=train.data$Class)
table(down_train$Class)

set.seed(5627)
# Build down-sampled model
down_fit <- rpart(Class ~ ., data = down_train)

# AUC on down-sampled data
pred_down <- predict(down_fit, newdata = test.data)

print('Fitting model to downsampled data')
roc.curve(test.data$Class, pred_down[,2], plotit = TRUE)


```

```{r upsampling}

set.seed(12345)
up_train <- upSample(x = train.data[, -30],
  y = train.data$Class)

table(up_train$Class)

set.seed(5627)
# Build up-sampled model
up_fit <- rpart(Class ~ ., data = up_train)

# AUC on up-sampled data
pred_up <- predict(up_fit, newdata = test.data)

print('Fitting model to upsampled data')
roc.curve(test.data$Class, pred_up[,2], plotit = TRUE)

```

```{r SMOTE}

##SMOTE: Synthetic Minority Oversampling Technique to Handle Class Imbalance
## in Binary Classification

##setDF(train.data)
##class(train.data)

##set.seed(12345)

##solution<-matrix(table(train.data$Class))


#solution<-as.data.frame(table(unlist(record)))
#solution <-as.data.frame(train.data)	
#solution <- as.data.frame(table(unlist(train.data$Class)))  
##solution <- as.data.frame(train.data(unlist(record)))
##smote_train <- SMOTE(Class ~., solution)
                     ##perc.over = 4800, k = 5, perc.under = 1000) 
##smote_fit <- rpart(Class ~ ., data = smote_train)

##smote_train <- SMOTE(Class ~., data=train.data, perc.over = 4800, k = 5, perc.under = 1000)
##as.data.frame(table(smote_train$Class))
##table(smote_train$Class)
```

```{r ROSE}

# ROSE
set.seed(12345)
rose_train <- ROSE(Class ~ ., data  = train.data)$data 

table(rose_train$Class)

# ROSE model
set.seed(5627)
rose_fit <- rpart(Class ~ ., data = rose_train)

#AUC for ROSE model
pred_rose <- predict(rose_fit, newdata = test.data)


print('Fitting model to ROSE data')
roc.curve(test.data$Class, pred_rose[,2], plotit = TRUE)

```
