---
title: "BUAN6356_Group8_Project_CreditCardFraud"
author: "Stacey Kirkpatrick"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_notebook:
    theme: spacelab
    toc: yes
    toc_depth: 3
    toc_float: yes
  html_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Load packages

```{r loadpackages, warning=FALSE, message=FALSE, results='hide'}

if(!require("pacman")) install.packages("pacman")
pacman::p_load(data.table, tidyverse, ggplot2, ggcorrplot, pROC, ROSE,gains,
              corrplot, dplyr, caret, MASS, caTools, smotefamily, DMwR, rpart)

theme_set(theme_classic())
```

```{r logistic upsampled}

# Upsample Test Data
set.seed(12345)
up_test <- upSample(x = test.data[, -30], y = test.data$Class)

table(up_test$Class)

logit.reg <- glm(Class ~ ., data = up_train, family = "binomial")
options(scipen = 999) 
summary(logit.reg)

#Generate odds ratio
exp(coef(logit.reg))

#performance evaluation
logit.reg.pred <- predict(logit.reg, up_test, type = "response")

t(t(head(logit.reg.pred, 10)))

#confusion matrix
table(up_test$Class, logit.reg.pred > 0.5)

summary(logit.reg.pred)

acc2<-table(logit.reg.pred > 0.5, up_test$Class)
print("Confusion Matrix for Test Data")
acc2

#Precision score 
precision <- acc2[2,2]/(acc2[2,2]+acc2[2,1])
precision

#Recall
recall <- acc2[2,2]/(acc2[2,2]+acc2[1,2])
recall

#Specificity
specificity <- acc2[1,1]/(acc2[1,1]+acc2[2,1])
specificity

#F Score
fscore <- (precision*recall)/(precision+recall)
fscore


print('ROC')
roc.curve(up_test$Class, logit.reg.pred, plotit = TRUE)

```

